# Configurações da Aplicação FITSOCK E-commerce
server.port=8080
spring.application.name=fitsock-ecommerce

# Configurações do Thymeleaf (Desativa cache para desenvolvimento)
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Configurações de Recursos Estáticos
spring.web.resources.static-locations=classpath:/static/
